version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always
